### ISSUE TITLE
Minor allele error: AttributeError: 'Series' object has no attribute 'minor_allele'

### ISSUE THREAD

**Issue by malmarri** [35ajstern/palm#2]
Hi Aaron,

1) I was trying to run palm, I formatted the metadata file as illustrated in the [wiki](https://github.com/35ajstern/palm/wiki/3.-Metadata-&-input-organization-format). But receive the following error, I'm assuming there needs to be a column in the metadata with the minor allele? (the metadata wiki doesn't show such a column).

```
Analyzing trait...
Loading likelihoods...
Traceback (most recent call last):                                                                                                                                       ]   0%
  File "../palm/palm.py", line 287, in <module>
    _main(args)
  File "../palm/palm.py", line 257, in _main
    statistics = _parse_loci_stats(args)
  File "../palm/palm.py", line 88, in _parse_loci_stats
    minor_allele = dfRow.minor_allele
  File "/lustre/scratch114/projects/t19-appg/my-venv/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'minor_allele'
```
2) The wiki states that "betas measure the effect of the ALT allele". I just wanted to confirm this, since the minor allele frequency and the minor allele seem to be needed in the metadata file.
Thanks,
Mo

**Comment by 35ajstern** [comment]
Hi Mo!

thanks for pointing out this issue. 

I think I fixed it. Can you perform a git pull now and see if the issue's resolved?

I think the calls to 'df.minor_allele' and 'df.minor_AF' were vestigial, from an earlier version when I was actually including these columns in the metadata file -- but they are redundant, so I formatted the ones in the Wiki to not have those columns. 

I guess I didn't test that the code could handle that change; leaving in those ghost calls to 'df.minor_allele' and 'df.minor_AF' throws errors. 

In response to (2); yes, it's the effect of the ALT allele. Now that I fixed the bug, MAF and minor allele are NOT needed in the metadata file.

Thanks for checking this out,
Aaron

**Comment by malmarri** [comment]
Thanks for the quick reply!

It starts but runs into another error:

```
 python3 ../palm/palm.py --traitDir BLOCKS/ --metadata final_metadata4 --maxp 5e-8 --B 1000

Analyzing trait...
Loading likelihoods...
[========================================================================================================================================================================] 100%
Traceback (most recent call last):
  File "../palm/palm.py", line 281, in <module>
    _main(args)
  File "../palm/palm.py", line 252, in _main
    L_byTrait,L = _nloci(statistics,args)
  File "../palm/palm.py", line 179, in _nloci
    J = pvals.shape[1]
IndexError: tuple index out of range

```
