### ISSUE TITLE
No such file or directory file.palm

### ISSUE THREAD

**Issue by nurfatimaj** [35ajstern/palm#3]
Hi! 

I am trying to run PALM and following the instruction in wiki. I am currently trying to get SNP likelihoods. This is my code

`python3 lik.py --times ../1000g/file --popFreq 0.26 --out ../1000g/snps/ld_4/bp4569436`

But I get an error message saying "FileNotFoundError: [Errno 2] No such file or directory: '../1000g/file.palm'". Technically, I get it, the folder really doesn't have file.palm object, only file.timeb. But how do I obtain a palm file?

Thank you!

**Comment by nurfatimaj** [comment]
Actually, I just changed `.palm` to `.timeb` in line 87 and everything worked fine.

**Comment by 35ajstern** [comment]
closing issue
