### ISSUE TITLE
Error with shapes of pval and beta

### ISSUE THREAD

**Issue by nurfatimaj** [35ajstern/palm#4]
Hi!

I am now trying to run palm.py and keep getting this error: "IndexError: tuple index out of range" at line 179 of palm.py (`J = ovals.shape[1]`). I tried simply commenting it out since J from `_nloci()` function is not returned as output, but the same error appears when trying to assign J from shape of betas. 

<img width="902" alt="image" src="https://user-images.githubusercontent.com/24235395/91994883-67e0ee80-ed37-11ea-83b9-8655d45d1c29.png">

To make sure this is not because of wrong formatting of summary statistics, I tried to run it with the example data. But the error is still the same. 

I wanted to examine the issue with some print statements, but for some weird reason my print statements don't work.

Any help would be appreciated!

Thank you!

**Comment by 35ajstern** [comment]
Hmm. Can you first make sure this is not a version issue by pulling (git pull) the current version of master?

**Comment by nurfatimaj** [comment]
I cloned the repository only yesterday. I have tried running `git pull`, but it says "Already up to date."

**Comment by 35ajstern** [comment]
I'll make a note to add a statement to check for whether traitDir is missing a trailing backslash, and if so, that it also tries a path that includes the backslash.

**Comment by nurfatimaj** [comment]
> Ah, I see the problem. You are missing a trailing '/' from traitDir:
> 
> `--traitDir ~/Downloads/1000G_SNPs` --> `--traitDir ~/Downloads/1000G_SNPs/`

Thanks! This solved it!

**Comment by celianeto** [comment]
Hi!

I'm trying to run PALm and ran into the same problem. Do you think it is still a path issue? 

<img width="893" alt="Picture 1" src="https://user-images.githubusercontent.com/66737212/110115098-e76a7b80-7db5-11eb-8a9b-452e61e23b1b.png">

Thanks,
Célia
