### ISSUE TITLE
How to specify generation span to use in estimation?

### ISSUE THREAD

**Issue by nurfatimaj** [35ajstern/palm#5]
Hello!

I am trying to replicate the results in [Stern et al (2020) paper](https://www.biorxiv.org/content/10.1101/2020.05.07.083402v1). And I cannot understand how to implement this sentence: "We specifically tested for selection in the last 2000 years (i.e., 68.95 generations, assuming a generation time of 29 years)." 

- I couldn't find a suitable option in `palm.py`. 
- There seem to be some possibly relevant options in `lik.py`, but I am not sure since they are not described anywhere. 
- Or is this something I have to specify way before when running RELATE?

Thank you very much!

**Comment by 35ajstern** [comment]
Use the --kappa and --K options in lik.py. These are described in the wiki. In combination with the .coal file used while running RELATE, they specify the selection timescale.

**Comment by nurfatimaj** [comment]
Could I just check that I understood you correctly?
1. If I want to say that selection began in the last 68.95 generations, I need to set --K to 68.95.
2. If I want to say that selection took place in all that time I also need to set --kappa to 68.95
3. In addition I have to adjust the coal file to only include information in the last 68.95 generations. So, if coal file has coalescence rate over more generations in the past, I have to delete them.

Is that correct?  Does it also correspond exactly to the sentence from the paper?

Thanks a lot!

**Comment by 35ajstern** [comment]
No that's incorrect. please see https://github.com/35ajstern/palm/wiki/2.-SNP-likelihoods. I updated the documentation to illustrate the usage with an example.

**Comment by nurfatimaj** [comment]
Ah, that helps a lot! Thank you very much!
