### ISSUE TITLE
Code "improvement" suggestions

### ISSUE THREAD

**Issue by nurfatimaj** [35ajstern/palm#7]
Hello!

Can I suggest the following changes to the code?

1. Should this line https://github.com/35ajstern/palm/blob/31ad155df23c667a45cd78f1d8ef06fd9d480e96/lik.py#L87
be changed to `locusDerTimes,locusAncTimes = parse_clues(args.times+'.timeb')`? I have created a pull request #6 for this.
2. When I tried to test for selection in the last 8 epochs, I received a "division by zero" error when estimating likelihood in one of the SNPs. I managed to get around it by adding/subtracting `bit` in following lines:
    https://github.com/35ajstern/palm/blob/31ad155df23c667a45cd78f1d8ef06fd9d480e96/palm_utils/deterministic_utils.py#L89
    https://github.com/35ajstern/palm/blob/31ad155df23c667a45cd78f1d8ef06fd9d480e96/palm_utils/deterministic_utils.py#L92
    https://github.com/35ajstern/palm/blob/31ad155df23c667a45cd78f1d8ef06fd9d480e96/palm_utils/deterministic_utils.py#L118
    https://github.com/35ajstern/palm/blob/31ad155df23c667a45cd78f1d8ef06fd9d480e96/palm_utils/deterministic_utils.py#L121
    But I am not sure how legit this fix is? Could you please have a look?

Thanks a lot!

**Comment by 35ajstern** [comment]
Hi! Busy week for me but 

(1) I will implement (i thought I fixed this before...sorry!) 

and (2) i don't think this is a valid fix, as bit (iirc) is an important variable that determines allele polarization.

Can you send me a minimal reproducible example? (ajstern at-sign berkeley dot edu)
