### ISSUE TITLE
Another potential bug in palm.py?

### ISSUE THREAD

**Issue by nurfatimaj** [35ajstern/palm#8]
Hi!

I think there is potentially another little bug in palm.py. I have been receiving error that ses has been called before being defined and that x0 is undefined. Once I commented out these lines

https://github.com/35ajstern/palm/blob/8426f956d86cd9edb266519fcd34d6bce5a3e76d/palm.py#L236-L237

PALM has finished without errors. As far as I could see these lines were inconsequential in a sense that they were not actually used.

Could you please have a look?

Thank you!

**Comment by 35ajstern** [comment]
Yes I think this is correct. Thanks!
